/**
 * GENERATED FILE -- do not edit by hand.
 * Regenerate with: node scripts/gen-schema-map.cjs
 *
 * Maps each old Firestore collection onto the Supabase view it reads from and
 * the table it writes to, plus the camelCase -> column translation for writes.
 * Derived from the live view definitions, so renames such as
 * orderId -> order_no are exact rather than guessed.
 *
 * `derived` lists keys the view computes (joins, aggregates, formatted dates).
 * They can be read but never written, and db.js drops them from writes.
 */

export const SCHEMA_MAP = {
  "accounts": {
    "view": "fs_accounts",
    "table": "accounts",
    "fields": {
      "id": "id",
      "name": "name",
      "type": "type",
      "isBank": "is_bank",
      "openingBalanceNPR": "opening_balance_npr",
      "createdAt": "created_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "created_at",
      "id",
      "is_bank",
      "name",
      "opening_balance_npr",
      "region",
      "type"
    ]
  },
  "attendance": {
    "view": "fs_attendance",
    "table": "attendance",
    "fields": {
      "id": "id",
      "date": "date",
      "status": "status",
      "hours": "hours",
      "lateMinutes": "late_minutes",
      "lateCutApplied": "late_cut_applied",
      "note": "note",
      "loggedBy": "logged_by",
      "staffName": "legacy_staff_name",
      "role": "legacy_role",
      "person_id": "person_id",
      "createdAt": "created_at"
    },
    "derived": [
      "staffId",
      "region"
    ],
    "columns": [
      "created_at",
      "date",
      "hours",
      "id",
      "late_cut_applied",
      "late_minutes",
      "legacy_role",
      "legacy_staff_id",
      "legacy_staff_name",
      "logged_by",
      "note",
      "person_id",
      "status"
    ]
  },
  "bank_transactions": {
    "view": "fs_bank_transactions",
    "table": "bank_transactions",
    "fields": {
      "id": "id",
      "timestamp": "txn_at",
      "type": "type",
      "amount": "amount",
      "balance": "balance",
      "description": "description",
      "remarks": "remarks",
      "createdAt": "created_at",
      "region": "region"
    },
    "derived": [
      "date"
    ],
    "columns": [
      "amount",
      "balance",
      "created_at",
      "description",
      "id",
      "region",
      "remarks",
      "txn_at",
      "txn_date_text",
      "type"
    ]
  },
  "budget_requests": {
    "view": "fs_budget_requests",
    "table": "budget_requests",
    "fields": {
      "id": "id",
      "brId": "br_ref",
      "title": "title",
      "type": "type",
      "category": "category",
      "urgency": "urgency",
      "quantity": "quantity",
      "notes": "notes",
      "amount": "amount",
      "amountNPR": "amount_npr",
      "amountGBP": "amount_gbp",
      "status": "status",
      "requestedBy": "requested_by",
      "requestedByRole": "requested_by_role",
      "reviewedBy": "reviewed_by",
      "reviewedAt": "reviewed_at",
      "createdAt": "created_at",
      "requested_by_id": "requested_by_id",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "amount",
      "amount_gbp",
      "amount_npr",
      "br_ref",
      "category",
      "created_at",
      "id",
      "notes",
      "quantity",
      "region",
      "requested_by",
      "requested_by_id",
      "requested_by_role",
      "reviewed_at",
      "reviewed_by",
      "status",
      "title",
      "type",
      "urgency"
    ]
  },
  "challans": {
    "view": "fs_challans",
    "table": "challans",
    "fields": {
      "id": "id",
      "challanNumber": "challan_no",
      "clientName": "client_name",
      "clientAddress": "client_address",
      "clientPhone": "client_phone",
      "clientPAN": "client_pan",
      "currency": "currency",
      "date": "challan_date",
      "fiscalYear": "fiscal_year",
      "subtotalNPR": "subtotal_npr",
      "discountPct": "discount_pct",
      "discountAmtNPR": "discount_amt_npr",
      "taxableAmtNPR": "taxable_amt_npr",
      "vatAmountNPR": "vat_amount_npr",
      "totalNPR": "total_npr",
      "status": "status",
      "vehicleNo": "vehicle_no",
      "driverName": "driver_name",
      "routeFrom": "route_from",
      "routeTo": "route_to",
      "relatedInvoice": "related_invoice",
      "note": "note",
      "createdBy": "created_by",
      "updatedBy": "updated_by",
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      "discountMode": "discount_mode",
      "discountFlatAmt": "discount_flat_amt",
      "region": "region"
    },
    "derived": [
      "items"
    ],
    "columns": [
      "challan_date",
      "challan_no",
      "client_address",
      "client_name",
      "client_pan",
      "client_phone",
      "created_at",
      "created_by",
      "currency",
      "discount_amt_npr",
      "discount_flat_amt",
      "discount_mode",
      "discount_pct",
      "driver_name",
      "fiscal_year",
      "id",
      "linked_order_id",
      "note",
      "region",
      "related_invoice",
      "route_from",
      "route_to",
      "status",
      "subtotal_npr",
      "taxable_amt_npr",
      "total_npr",
      "updated_at",
      "updated_by",
      "vat_amount_npr",
      "vehicle_no"
    ]
  },
  "clock_ins": {
    "view": "fs_clock_ins",
    "table": "clock_ins",
    "fields": {
      "id": "id",
      "date": "date",
      "clockedInAt": "clocked_in_at",
      "clockedOutAt": "clocked_out_at",
      "workedHours": "worked_hours",
      "lat": "lat",
      "lng": "lng",
      "accuracyM": "accuracy_m",
      "distanceToSiteM": "distance_to_site_m",
      "bypassUsed": "bypass_used",
      "staffName": "legacy_staff_name",
      "role": "legacy_role",
      "person_id": "person_id"
    },
    "derived": [
      "staffId",
      "region"
    ],
    "columns": [
      "accuracy_m",
      "bypass_used",
      "clocked_in_at",
      "clocked_out_at",
      "created_at",
      "date",
      "distance_to_site_m",
      "id",
      "lat",
      "legacy_role",
      "legacy_staff_id",
      "legacy_staff_name",
      "lng",
      "person_id",
      "worked_hours"
    ]
  },
  "content": {
    "view": "fs_content",
    "table": "content_posts",
    "fields": {
      "id": "id",
      "topic": "topic",
      "contentType": "content_type",
      "platform": "platform",
      "status": "status",
      "date": "post_date",
      "createdBy": "created_by",
      "createdAt": "created_at"
    },
    "derived": [],
    "columns": [
      "content_type",
      "created_at",
      "created_by",
      "id",
      "platform",
      "post_date",
      "status",
      "topic"
    ]
  },
  "content_calendar": {
    "view": "fs_content_calendar",
    "table": "content_calendar",
    "fields": {
      "id": "id",
      "title": "title",
      "type": "type",
      "status": "status",
      "scheduledDate": "scheduled_date",
      "timeSlot": "time_slot",
      "notes": "notes",
      "mediaUrl": "media_url",
      "createdAt": "created_at"
    },
    "derived": [],
    "columns": [
      "created_at",
      "id",
      "media_url",
      "notes",
      "scheduled_date",
      "status",
      "time_slot",
      "title",
      "type"
    ]
  },
  "counters": {
    "view": "fs_counters",
    "table": "counters",
    "fields": {
      "id": "id",
      "nextInvoice": "next_invoice",
      "nextQuotation": "next_quotation"
    },
    "derived": [],
    "columns": [
      "id",
      "next_challan",
      "next_invoice",
      "next_quotation"
    ]
  },
  "customers": {
    "view": "fs_customers",
    "table": "customers",
    "fields": {
      "id": "id",
      "name": "name",
      "contactPerson": "contact_person",
      "email": "email",
      "phone": "phone",
      "address": "address",
      "city": "city",
      "country": "country",
      "notes": "notes",
      "createdAt": "created_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "address",
      "city",
      "contact_person",
      "country",
      "created_at",
      "email",
      "id",
      "name",
      "notes",
      "phone",
      "region",
      "updated_at"
    ]
  },
  "employees": {
    "view": "fs_employees",
    "table": "people",
    "fields": {
      "id": "id",
      "name": "full_name",
      "email": "email",
      "positionId": "position_id",
      "status": "status",
      "location": "location",
      "department": "department",
      "isProductionWorker": "is_production_worker",
      "scheduleStart": "schedule_start",
      "scheduleEnd": "schedule_end",
      "scheduleWorkingDays": "schedule_working_days",
      "scheduleDayOverrides": "schedule_day_overrides",
      "scheduleNote": "schedule_note",
      "uid": "legacy_firebase_uid",
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      "phone": "phone",
      "address": "address",
      "basicSalaryNPR": "basic_salary_npr",
      "bankName": "bank_name",
      "bankBranch": "bank_branch",
      "bankAccount": "bank_account",
      "panNumber": "pan_number",
      "joinDate": "join_date",
      "telegramId": "telegram_id",
      "region": "location"
    },
    "derived": [
      "role"
    ],
    "columns": [
      "address",
      "auth_uid",
      "bank_account",
      "bank_branch",
      "bank_name",
      "basic_salary_npr",
      "created_at",
      "department",
      "email",
      "fcm_token",
      "full_name",
      "id",
      "is_production_worker",
      "join_date",
      "legacy_firebase_uid",
      "location",
      "notes",
      "pan_number",
      "phone",
      "position_id",
      "reports_to",
      "schedule_day_overrides",
      "schedule_end",
      "schedule_note",
      "schedule_start",
      "schedule_working_days",
      "status",
      "telegram_id",
      "updated_at"
    ]
  },
  "fabrics": {
    "view": "fs_fabrics",
    "table": "fabrics",
    "fields": {
      "id": "id",
      "name": "name",
      "type": "type",
      "composition": "composition",
      "supplier": "supplier",
      "gsm": "gsm",
      "weight": "weight",
      "price_per_meter": "price_per_meter",
      "pricePerKg": "price_per_kg",
      "available_colors": "available_colors",
      "status": "status",
      "notes": "notes",
      "swatchImageUrl": "swatch_image_url",
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "available_colors",
      "composition",
      "created_at",
      "gsm",
      "id",
      "name",
      "notes",
      "price_per_kg",
      "price_per_meter",
      "region",
      "status",
      "supplier",
      "swatch_image_url",
      "type",
      "updated_at",
      "weight"
    ]
  },
  "finance_expenses": {
    "view": "fs_finance_expenses",
    "table": "expenses",
    "fields": {
      "id": "id",
      "date": "expense_date",
      "category": "category",
      "amountNPR": "amount_npr",
      "note": "note",
      "status": "status",
      "vatBill": "vat_bill",
      "loggedBy": "logged_by",
      "createdAt": "created_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "amount_npr",
      "category",
      "created_at",
      "expense_date",
      "id",
      "logged_by",
      "note",
      "region",
      "status",
      "vat_bill"
    ]
  },
  "finance_payroll": {
    "view": "fs_finance_payroll",
    "table": "payroll",
    "fields": {
      "id": "id",
      "month": "month",
      "year": "year",
      "basicNPR": "basic_npr",
      "salaryNPR": "salary_npr",
      "bonusNPR": "bonus_npr",
      "overtimeNPR": "overtime_npr",
      "deductionNPR": "deduction_npr",
      "pfDeductionNPR": "pf_deduction_npr",
      "lateDeductionNPR": "late_deduction_npr",
      "lateDays": "late_days",
      "lateCutsCount": "late_cuts_count",
      "totalDeductionsNPR": "total_deductions_npr",
      "grossNPR": "gross_npr",
      "netNPR": "net_npr",
      "note": "note",
      "loggedBy": "logged_by",
      "staffId": "legacy_staff_id",
      "staffName": "legacy_staff_name",
      "role": "legacy_role",
      "person_id": "person_id"
    },
    "derived": [
      "region"
    ],
    "columns": [
      "basic_npr",
      "bonus_npr",
      "created_at",
      "deduction_npr",
      "gross_npr",
      "id",
      "late_cuts_count",
      "late_days",
      "late_deduction_npr",
      "legacy_role",
      "legacy_staff_id",
      "legacy_staff_name",
      "logged_by",
      "month",
      "net_npr",
      "note",
      "overtime_npr",
      "person_id",
      "pf_deduction_npr",
      "salary_npr",
      "total_deductions_npr",
      "year"
    ]
  },
  "finance_purchases": {
    "view": "fs_finance_purchases",
    "table": "purchases",
    "fields": {
      "id": "id",
      "expenseId": "expense_ref",
      "date": "purchase_date",
      "expenseItem": "expense_item",
      "category": "category",
      "amountNPR": "amount_npr",
      "subtotalNPR": "subtotal_npr",
      "discountAmt": "discount_amt",
      "taxableAmt": "taxable_amt",
      "vatAmountNPR": "vat_amount_npr",
      "vatBill": "vat_bill",
      "paymentType": "payment_type",
      "bankName": "bank_name",
      "createdAt": "created_at",
      "region": "region"
    },
    "derived": [
      "items"
    ],
    "columns": [
      "amount_npr",
      "bank_name",
      "category",
      "created_at",
      "discount_amt",
      "expense_item",
      "expense_ref",
      "id",
      "payment_type",
      "purchase_date",
      "region",
      "subtotal_npr",
      "taxable_amt",
      "vat_amount_npr",
      "vat_bill"
    ]
  },
  "inventory": {
    "view": "fs_inventory",
    "table": "inventory_items",
    "fields": {
      "id": "id",
      "itemId": "item_ref",
      "item": "item",
      "category": "category",
      "unit": "unit",
      "supplier": "supplier",
      "location": "location",
      "condition": "condition",
      "owner": "owner",
      "openingStock": "opening_stock",
      "stockIn": "stock_in",
      "stockUsed": "stock_used",
      "minLevel": "min_level",
      "unitCostNPR": "unit_cost_npr",
      "sizeRows": "size_rows",
      "damageLog": "damage_log",
      "lastUpdated": "last_updated",
      "createdBy": "created_by",
      "updatedBy": "updated_by",
      "createdAt": "created_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "category",
      "condition",
      "created_at",
      "created_by",
      "damage_log",
      "id",
      "item",
      "item_ref",
      "last_updated",
      "location",
      "min_level",
      "opening_stock",
      "owner",
      "region",
      "size_rows",
      "stock_in",
      "stock_used",
      "supplier",
      "unit",
      "unit_cost_npr",
      "updated_by"
    ]
  },
  "invoices": {
    "view": "fs_invoices",
    "table": "invoices",
    "fields": {
      "id": "id",
      "invoiceNumber": "invoice_no",
      "clientName": "client_name",
      "clientAddress": "client_address",
      "clientPhone": "client_phone",
      "clientPAN": "client_pan",
      "currency": "currency",
      "date": "invoice_date",
      "dueDate": "due_date",
      "fiscalYear": "fiscal_year",
      "applyVAT": "apply_vat",
      "subtotalNPR": "subtotal_npr",
      "discountPct": "discount_pct",
      "discountAmtNPR": "discount_amt_npr",
      "taxableAmtNPR": "taxable_amt_npr",
      "vatAmountNPR": "vat_amount_npr",
      "totalNPR": "total_npr",
      "amountPaid": "amount_paid",
      "status": "status",
      "paymentTerms": "payment_terms",
      "paymentType": "payment_type",
      "bankName": "bank_name",
      "relatedQuotation": "related_quotation",
      "relatedChallan": "related_challan",
      "challanNumber": "challan_number",
      "note": "note",
      "createdBy": "created_by",
      "updatedBy": "updated_by",
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      "discountMode": "discount_mode",
      "discountFlatAmt": "discount_flat_amt",
      "linkedOrderId": "linked_order_id",
      "region": "region"
    },
    "derived": [
      "items"
    ],
    "columns": [
      "amount_paid",
      "apply_vat",
      "bank_name",
      "challan_number",
      "client_address",
      "client_name",
      "client_pan",
      "client_phone",
      "created_at",
      "created_by",
      "currency",
      "discount_amt_npr",
      "discount_flat_amt",
      "discount_mode",
      "discount_pct",
      "due_date",
      "fiscal_year",
      "id",
      "invoice_date",
      "invoice_no",
      "linked_order_id",
      "note",
      "payment_terms",
      "payment_type",
      "region",
      "related_challan",
      "related_quotation",
      "status",
      "subtotal_npr",
      "taxable_amt_npr",
      "total_npr",
      "updated_at",
      "updated_by",
      "vat_amount_npr"
    ]
  },
  "journal_entries": {
    "view": "fs_journal_entries",
    "table": "journal_entries",
    "fields": {
      "id": "id",
      "date": "entry_date",
      "debitAccount": "debit_account",
      "creditAccount": "credit_account",
      "amountNPR": "amount_npr",
      "description": "description",
      "reference": "reference",
      "createdBy": "created_by",
      "createdAt": "created_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "amount_npr",
      "created_at",
      "created_by",
      "credit_account",
      "debit_account",
      "description",
      "entry_date",
      "id",
      "reference",
      "region"
    ]
  },
  "leaderboard": {
    "view": null,
    "table": "leaderboard",
    "fields": {
      "id": "id",
      "all_time": "all_time",
      "weekly": "weekly",
      "last_updated": "last_updated"
    },
    "derived": [],
    "columns": [
      "all_time",
      "id",
      "last_updated",
      "weekly"
    ]
  },
  "messages": {
    "view": "fs_messages",
    "table": "messages",
    "fields": {
      "id": "id",
      "senderId": "legacy_sender_id",
      "text": "text",
      "timestamp": "sent_at",
      "sender_id": "sender_id",
      "threadId": "thread_id"
    },
    "derived": [],
    "columns": [
      "id",
      "legacy_sender_id",
      "sender_id",
      "sent_at",
      "text",
      "thread_id"
    ]
  },
  "order_assignments": {
    "view": "fs_order_assignments",
    "table": "order_assignments",
    "fields": {
      "id": "id",
      "orderId": "order_id",
      "orderRef": "order_ref",
      "assignedTo": "assigned_to",
      "workerName": "assigned_to",
      "personId": "person_id",
      "workerId": "person_id",
      "workerTelegramId": "worker_telegram_id",
      "customerName": "customer_name",
      "quantity": "quantity",
      "stage": "stage",
      "status": "status",
      "assignedAt": "assigned_at",
      "acceptedAt": "accepted_at",
      "completedAt": "completed_at",
      "timeoutAt": "timeout_at",
      "timeoutHours": "timeout_hours",
      "notifiedManager": "notified_manager",
      "assignedBy": "assigned_by",
      "note": "note",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "accepted_at",
      "assigned_at",
      "assigned_by",
      "assigned_to",
      "completed_at",
      "customer_name",
      "id",
      "note",
      "notified_manager",
      "order_id",
      "order_ref",
      "person_id",
      "quantity",
      "region",
      "stage",
      "status",
      "timeout_at",
      "timeout_hours",
      "worker_telegram_id"
    ]
  },
  "order_costs": {
    "view": "fs_order_costs",
    "table": "order_costs",
    "fields": {
      "id": "id",
      "orderId": "order_ref",
      "orderRef": "order_ref",
      "linkedOrderId": "order_id",
      "material": "material_npr",
      "labour": "labour_npr",
      "overhead": "overhead_npr",
      "shipping": "shipping_npr",
      "totalNPR": "total_npr",
      "note": "note",
      "createdBy": "created_by",
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "created_at",
      "created_by",
      "id",
      "labour_npr",
      "material_npr",
      "note",
      "order_id",
      "order_ref",
      "overhead_npr",
      "region",
      "shipping_npr",
      "total_npr",
      "updated_at"
    ]
  },
  "orders": {
    "view": "fs_orders",
    "table": "orders",
    "fields": {
      "id": "id",
      "orderId": "order_no",
      "customerName": "customer_name",
      "styleName": "style_name",
      "colorway": "colorway",
      "fabricType": "fabric_type",
      "quantity": "quantity",
      "pricePerPcNPR": "price_per_pc_npr",
      "totalValueNPR": "total_value_npr",
      "fabricCostPerPcNPR": "fabric_cost_per_pc_npr",
      "fabricGramsUsed": "fabric_grams_used",
      "fabricRequiredPerPc": "fabric_required_per_pc",
      "materialCostTotalNPR": "material_cost_total_npr",
      "stage": "stage",
      "status": "status",
      "date": "order_date",
      "deliveryDate": "delivery_date",
      "invoiceRef": "invoice_ref",
      "sampleName": "sample_name",
      "notes": "notes",
      "createdBy": "created_by",
      "createdAt": "created_at",
      "customer_id": "customer_id",
      "assigned_to": "assigned_to",
      "embellishments": "embellishments",
      "sampleId": "sample_id",
      "region": "region"
    },
    "derived": [
      "assignedTo",
      "stageHistory",
      "notesList"
    ],
    "columns": [
      "assigned_to",
      "colorway",
      "created_at",
      "created_by",
      "customer_id",
      "customer_name",
      "delivery_date",
      "embellishments",
      "fabric_cost_per_pc_npr",
      "fabric_grams_used",
      "fabric_required_per_pc",
      "fabric_type",
      "id",
      "invoice_ref",
      "material_cost_total_npr",
      "notes",
      "order_date",
      "order_no",
      "price_per_pc_npr",
      "quantity",
      "region",
      "sample_id",
      "sample_name",
      "stage",
      "status",
      "style_name",
      "total_value_npr",
      "updated_at"
    ]
  },
  "patterns": {
    "view": "fs_patterns",
    "table": "patterns",
    "fields": {
      "id": "id",
      "styleNo": "style_no",
      "name": "name",
      "product_type": "product_type",
      "category": "category",
      "season": "season",
      "market": "market",
      "designerName": "designer_name",
      "sizes_available": "sizes_available",
      "available_colors": "available_colors",
      "specSize": "spec_size",
      "specDate": "spec_date",
      "trims": "trims",
      "washCare": "wash_care",
      "remarks": "remarks",
      "notes": "notes",
      "measurements": "measurements",
      "fabricRows": "fabric_rows",
      "frontSketchUrl": "front_sketch_url",
      "backSketchUrl": "back_sketch_url",
      "tech_pack_url": "tech_pack_url",
      "tech_pack_images": "tech_pack_images",
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "available_colors",
      "back_sketch_url",
      "category",
      "created_at",
      "designer_name",
      "fabric_rows",
      "front_sketch_url",
      "id",
      "market",
      "measurements",
      "name",
      "notes",
      "product_type",
      "region",
      "remarks",
      "season",
      "sizes_available",
      "spec_date",
      "spec_size",
      "style_no",
      "tech_pack_images",
      "tech_pack_url",
      "trims",
      "updated_at",
      "wash_care"
    ]
  },
  "positions": {
    "view": null,
    "table": "positions",
    "fields": {
      "id": "id",
      "label": "label",
      "tier": "tier",
      "description": "description"
    },
    "derived": [],
    "columns": [
      "description",
      "id",
      "label",
      "tier"
    ]
  },
  "sections": {
    "view": null,
    "table": "sections",
    "fields": {
      "id": "id",
      "label": "label",
      "aliases": "aliases",
      "is_personal": "is_personal",
      "sort_order": "sort_order"
    },
    "derived": [],
    "columns": [
      "aliases",
      "id",
      "is_personal",
      "label",
      "sort_order"
    ]
  },
  "finance_tabs": {
    "view": null,
    "table": "finance_tabs",
    "fields": {
      "id": "id",
      "label": "label",
      "sort_order": "sort_order"
    },
    "derived": [],
    "columns": [
      "id",
      "label",
      "sort_order"
    ]
  },
  "position_permissions": {
    "view": null,
    "table": "position_permissions",
    "fields": {
      "position_id": "position_id",
      "section_id": "section_id",
      "can_view": "can_view",
      "can_edit": "can_edit"
    },
    "derived": [],
    "columns": [
      "can_edit",
      "can_view",
      "position_id",
      "section_id"
    ]
  },
  "position_finance_tabs": {
    "view": null,
    "table": "position_finance_tabs",
    "fields": {
      "position_id": "position_id",
      "tab_id": "tab_id",
      "can_view": "can_view",
      "can_edit": "can_edit"
    },
    "derived": [],
    "columns": [
      "can_edit",
      "can_view",
      "position_id",
      "tab_id"
    ]
  },
  "point_transactions": {
    "view": null,
    "table": "point_transactions",
    "fields": {
      "id": "id",
      "person_id": "person_id",
      "event_type": "event_type",
      "source_id": "source_id",
      "points": "points",
      "reason": "reason",
      "awarded_at": "awarded_at"
    },
    "derived": [],
    "columns": [
      "awarded_at",
      "event_type",
      "id",
      "person_id",
      "points",
      "reason",
      "source_id"
    ]
  },
  "processes": {
    "view": "fs_processes",
    "table": "processes",
    "fields": {
      "id": "id",
      "name": "name",
      "category": "category",
      "description": "description",
      "notes": "notes",
      "cost_per_unit": "cost_per_unit",
      "lead_time_days": "lead_time_days",
      "min_quantity": "min_quantity",
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "category",
      "cost_per_unit",
      "created_at",
      "description",
      "id",
      "lead_time_days",
      "min_quantity",
      "name",
      "notes",
      "region",
      "updated_at"
    ]
  },
  "product_costs": {
    "view": "fs_product_costs",
    "table": "product_costs",
    "fields": {
      "id": "code",
      "code": "code",
      "name": "name",
      "fabric": "fabric",
      "labour": "labour",
      "rib": "rib",
      "trims": "trims",
      "others": "others",
      "total": "total",
      "updatedAt": "updated_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "code",
      "fabric",
      "labour",
      "name",
      "others",
      "region",
      "rib",
      "total",
      "trims",
      "updated_at"
    ]
  },
  "production": {
    "view": "fs_production",
    "table": "production_batches",
    "fields": {
      "id": "id",
      "batchId": "batch_ref",
      "date": "batch_date",
      "cut": "cut",
      "stitched": "stitched",
      "passed": "passed",
      "rejected": "rejected",
      "note": "note",
      "loggedBy": "logged_by",
      "createdAt": "created_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "batch_date",
      "batch_ref",
      "created_at",
      "cut",
      "id",
      "logged_by",
      "note",
      "passed",
      "region",
      "rejected",
      "stitched"
    ]
  },
  "qc_logs": {
    "view": "fs_qc_logs",
    "table": "qc_logs",
    "fields": {
      "id": "id",
      "qcId": "qc_ref",
      "batchId": "batch_ref",
      "date": "log_date",
      "inspected": "inspected",
      "passed": "passed",
      "rejected": "rejected",
      "defectType": "defect_type",
      "action": "action",
      "checkedBy": "checked_by",
      "createdAt": "created_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "action",
      "batch_ref",
      "checked_by",
      "created_at",
      "defect_type",
      "id",
      "inspected",
      "log_date",
      "passed",
      "qc_ref",
      "region",
      "rejected"
    ]
  },
  "quotations": {
    "view": "fs_quotations",
    "table": "quotations",
    "fields": {
      "id": "id",
      "quotationNumber": "quotation_no",
      "clientName": "client_name",
      "clientAddress": "client_address",
      "clientPhone": "client_phone",
      "clientPAN": "client_pan",
      "currency": "currency",
      "date": "quote_date",
      "validUntil": "valid_until",
      "subtotalNPR": "subtotal_npr",
      "discountPct": "discount_pct",
      "discountAmtNPR": "discount_amt_npr",
      "taxableAmtNPR": "taxable_amt_npr",
      "vatAmountNPR": "vat_amount_npr",
      "totalNPR": "total_npr",
      "status": "status",
      "terms": "terms",
      "note": "note",
      "relatedInvoice": "related_invoice",
      "createdBy": "created_by",
      "updatedBy": "updated_by",
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      "discountMode": "discount_mode",
      "discountFlatAmt": "discount_flat_amt",
      "region": "region"
    },
    "derived": [
      "items"
    ],
    "columns": [
      "client_address",
      "client_name",
      "client_pan",
      "client_phone",
      "created_at",
      "created_by",
      "currency",
      "discount_amt_npr",
      "discount_flat_amt",
      "discount_mode",
      "discount_pct",
      "id",
      "note",
      "quotation_no",
      "quote_date",
      "region",
      "related_invoice",
      "status",
      "subtotal_npr",
      "taxable_amt_npr",
      "terms",
      "total_npr",
      "updated_at",
      "updated_by",
      "valid_until",
      "vat_amount_npr"
    ]
  },
  "samples": {
    "view": "fs_samples",
    "table": "samples",
    "fields": {
      "id": "id",
      "name": "name",
      "product_type": "product_type",
      "stage": "stage",
      "status": "status",
      "fabric_used": "fabric_used",
      "size": "size",
      "color": "color",
      "cost": "cost",
      "photo_url": "photo_url",
      "notes": "notes",
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "color",
      "cost",
      "created_at",
      "fabric_used",
      "id",
      "name",
      "notes",
      "photo_url",
      "product_type",
      "region",
      "size",
      "stage",
      "status",
      "updated_at"
    ]
  },
  "stage_config": {
    "view": "fs_stage_config",
    "table": "stage_config",
    "fields": {
      "id": "stage",
      "stage": "stage",
      "enabled": "enabled",
      "order": "sort_order",
      "timeoutHours": "timeout_hours",
      "workerNames": "worker_names",
      "workerUids": "worker_uids"
    },
    "derived": [],
    "columns": [
      "enabled",
      "sort_order",
      "stage",
      "timeout_hours",
      "worker_names",
      "worker_uids"
    ]
  },
  "stock_movements": {
    "view": "fs_stock_movements",
    "table": "stock_movements",
    "fields": {
      "id": "id",
      "itemId": "item_id",
      "date": "moved_on",
      "qty": "qty",
      "direction": "direction",
      "source": "source",
      "sourceId": "source_id",
      "amountNPR": "amount_npr",
      "note": "note",
      "createdBy": "created_by",
      "createdAt": "created_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "amount_npr",
      "created_at",
      "created_by",
      "direction",
      "id",
      "item_id",
      "moved_on",
      "note",
      "qty",
      "region",
      "source",
      "source_id"
    ]
  },
  "task_columns": {
    "view": "fs_task_columns",
    "table": "task_columns",
    "fields": {
      "id": "id",
      "label": "label",
      "order": "sort_order",
      "tone": "tone"
    },
    "derived": [],
    "columns": [
      "id",
      "label",
      "sort_order",
      "tone"
    ]
  },
  "tasks": {
    "view": "fs_tasks",
    "table": "tasks",
    "fields": {
      "id": "id",
      "title": "title",
      "description": "description",
      "notes": "notes",
      "status": "status",
      "priority": "priority",
      "category": "category",
      "assignee": "assignee",
      "customer": "customer",
      "orderRef": "order_ref",
      "dueDate": "due_date",
      "createdBy": "created_by",
      "createdAt": "created_at",
      "assignee_id": "assignee_id",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "assignee",
      "assignee_id",
      "category",
      "created_at",
      "created_by",
      "customer",
      "description",
      "due_date",
      "id",
      "notes",
      "order_ref",
      "priority",
      "region",
      "status",
      "title",
      "updated_at"
    ]
  },
  "unit_economics": {
    "view": "fs_unit_economics",
    "table": "unit_economics",
    "fields": {
      "id": "id",
      "data": "data",
      "createdAt": "created_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "created_at",
      "data",
      "id",
      "region"
    ]
  },
  "user_points": {
    "view": "fs_user_points",
    "table": "user_points",
    "fields": {
      "id": "person_id",
      "personId": "person_id",
      "displayName": "display_name",
      "totalPoints": "total_points",
      "weeklyPoints": "weekly_points",
      "lastUpdated": "last_updated"
    },
    "derived": [],
    "columns": [
      "display_name",
      "last_updated",
      "person_id",
      "total_points",
      "weekly_points"
    ]
  },
  "users": {
    "view": "fs_users",
    "table": "people",
    "fields": {
      "id": "legacy_firebase_uid",
      "uid": "legacy_firebase_uid",
      "name": "full_name",
      "email": "email",
      "location": "location",
      "status": "status",
      "personId": "id",
      "region": "location"
    },
    "derived": [
      "jobRole",
      "tier"
    ],
    "columns": [
      "address",
      "auth_uid",
      "bank_account",
      "bank_branch",
      "bank_name",
      "basic_salary_npr",
      "created_at",
      "department",
      "email",
      "fcm_token",
      "full_name",
      "id",
      "is_production_worker",
      "join_date",
      "legacy_firebase_uid",
      "location",
      "notes",
      "pan_number",
      "phone",
      "position_id",
      "reports_to",
      "schedule_day_overrides",
      "schedule_end",
      "schedule_note",
      "schedule_start",
      "schedule_working_days",
      "status",
      "telegram_id",
      "updated_at"
    ]
  },
  "vat_bills": {
    "view": "fs_vat_bills",
    "table": "vat_bills",
    "fields": {
      "id": "id",
      "expenseId": "expense_id",
      "expenseItem": "expense_item",
      "fileName": "file_name",
      "fileUrl": "file_url",
      "storagePath": "storage_path",
      "fileType": "file_type",
      "source": "source",
      "uploadedBy": "uploaded_by",
      "uploadedAt": "uploaded_at",
      "region": "region"
    },
    "derived": [],
    "columns": [
      "expense_id",
      "expense_item",
      "file_name",
      "file_type",
      "file_url",
      "id",
      "region",
      "source",
      "storage_path",
      "uploaded_at",
      "uploaded_by"
    ]
  }
};

export default SCHEMA_MAP;
